// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCarShop.Models.Context;

#nullable disable

namespace MyCarShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20250520125719_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCarShop.Models.DomainModels.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Audi",
                            CarType = "Sedan",
                            Color = "Black",
                            ImageFileName = "CarDB_6.jpg",
                            Model = "A6",
                            Price = 22000.0m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes Benz",
                            CarType = "Sedan",
                            Color = "White",
                            ImageFileName = "CarDB_1.jpg",
                            Model = "MG 1",
                            Price = 95000.0m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            CarType = "Coupe",
                            Color = "Red",
                            ImageFileName = "CarDB_2.jpg",
                            Model = "M3",
                            Price = 67000.0m,
                            Year = 2025
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Aston Martin",
                            CarType = "Coupe",
                            Color = "Blue",
                            ImageFileName = "CarDB_10.jpg",
                            Model = "DB 12",
                            Price = 55000.0m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Ford",
                            CarType = "Pickup",
                            Color = "White",
                            ImageFileName = "CarDB_5.jpg",
                            Model = "Ranger",
                            Price = 34000.0m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Ferrari",
                            CarType = "Sport Car",
                            Color = "Red",
                            ImageFileName = "CarDB_4.jpg",
                            Model = "458 Italia",
                            Price = 99000.0m,
                            Year = 2025
                        },
                        new
                        {
                            Id = 7,
                            Brand = "BMW",
                            CarType = "Sedan",
                            Color = "Black",
                            ImageFileName = "CarDB_7.jpg",
                            Model = "M6",
                            Price = 80000.0m,
                            Year = 2025
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Lamborghini",
                            CarType = "Sport Car",
                            Color = "Green",
                            ImageFileName = "CarDB_3.jpg",
                            Model = "Gallard",
                            Price = 70000.0m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Mercedes Benz",
                            CarType = "Coupe",
                            Color = "White",
                            ImageFileName = "CarDB_8.jpg",
                            Model = "SLX",
                            Price = 45000.0m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Brand = "BMW",
                            CarType = "Sedan",
                            Color = "White",
                            ImageFileName = "CarDB_9.jpg",
                            Model = "M5",
                            Price = 44000.0m,
                            Year = 2024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
